module.exports = {
    home: {
        oils: 'Эфирные масла',
        care: 'Персональный уход',
        additives: 'Добавки',
        sets: 'Наборы',
        materials: 'Материалы',
        price: 'Прайс',
        catalog: 'Каталог',
        aromaTherapy: 'Ароматерапия для матери и ребенка',
        recipes: 'Рецепты',
        aromadesign: 'Аромадизайн',
        aromarecipes: 'Ароматерапия рецептуры',
        video: 'Видеоинструкции',
        emocionaroma: 'Эмоциональная ароматерапия',
    },
    oils: {
        single: 'Однокомпонентные',
        mixture: 'Смеси',
        dipblu: 'Дип блю',
        ongard: 'он Гард',
        accessory: 'Аксессуары',
    },
    care: {
        careBody: 'Уход за телом',
        spa: 'SPA – УХОД ЗА ЛИЦОМ И ТЕЛОМ',
        hair: 'Уход за волосами',
        face: 'Уход за кожей лица',
    },
    sets: {
        regSets: 'Регистрационные наборы',
        collections: 'Коллекции',
        leaderSets: 'Лидерские наборы',
    },
    materials: {
        litproduction: 'Литература о продукции',
        matforbuisness: 'Материалы для бизнеса',
    },
    additives: {
        cellhealth: 'Клеточное здоровье',
        kids: 'Добавки для детей',
        didgestZen: 'Продукция Дайджест Зен',
        slimSessi: 'Слим & Сесси',
        dolgozhitel: 'Долгожитель - комплекс добавок',
        cellEnergy: 'Клеточная энергия и здоровье',
        terraGrins: 'Терра Гринс',
        doterraWomen: 'dōTERRA® для женщин',
    },
    back: 'Назад',
}